### ISSUE TITLE
Доп Задача 5

### ISSUE THREAD

**Issue by keplian** [Rogozhin-Dmitry/yandex_lyceum_plus_plus#4]
- **Список категорий не выводится. Тэги тоже.**
<img width="677" alt="image" src="https://user-images.githubusercontent.com/45819480/162589695-97e82c13-49fe-4ea6-8ef6-cfc6e868913e.png">

**Comment by Rogozhin-Dmitry** [comment]
Вы уверены что это мой проект, и его последняя версия, PEP-8 то я сейчас поправлю, но вот актуальный скриншот, последняя версия с гита...
![image](https://user-images.githubusercontent.com/62459927/162590029-983f3e6d-61ef-48a7-b392-b8c67851d742.png)

**Comment by keplian** [comment]
Ох, прости, проверяю до дедлайна кучу работ, запостил не туда)

**Comment by keplian** [comment]
Твое, я проверил. Кто еще так базу то заполнит?) Почему то бд было заполнено пустыми значениями, удалил, скачал заново из твоего репозитория, вроде все ок стало.

Окей, замечания:
- **Сейчас на странице выводятся даже неопубликованные категории**

- **Если в БД нет неопубликованных товаров, то главная страница падает с ошибкой**
<img width="2274" alt="image" src="https://user-images.githubusercontent.com/45819480/162590424-291f9a60-0f6e-439b-9ad9-76d0ef8a4c82.png">

**Comment by Rogozhin-Dmitry** [comment]
О как, забавно, вот уж не думал что если я перетащу запросы из файла в файл начнутся беды, значит пойду исправлять

**Comment by Rogozhin-Dmitry** [comment]
Такс, видимо улучшить if просто уже физически невозможно :)) пришлось вернуть его на место, я вспомнил, почему не использовал random.sample изначально, всё оказалось очень просто, он падает в ошибку если в списке меньше 3 элементов, так что только через if
![image](https://user-images.githubusercontent.com/62459927/162591119-fca14a52-0c71-49b4-a8db-7eb42b491559.png)

А что касается категорий, да, огромная моя недоработка, но я с ней по быстрому смог решить только таким способом:
просто вытягивать из категории ещё и поле is_published, после чего просто проверять его в питоне, как наложить нормальный джанговский фильтр на select_related я понятия не имею, гуглить видимо тоже не умею, так что хоть что-то...


Поставьте пожалуйста баллов (жалобным голоском)
PEP-8 вроде тоже поправил

**Comment by keplian** [comment]
В общем, варианта 2. Если за неделю устранишь замечания, поставлю 10 баллов. Или можешь отказаться и зачту, но с 0

**Comment by Rogozhin-Dmitry** [comment]
Добрый день, вроде всё переделал, убрал хардкод, поправил pep8, во всяком случае flake8 перестал ругаться на импорты, сделал заготовку под рейтинг, но он пока не работает
