### ISSUE TITLE
Допзадача 7

### ISSUE THREAD

**Issue by keplian** [Rogozhin-Dmitry/yandex_lyceum_plus_plus#7]
- **При регистрации нового пользователя нет обработки ошибки уникальности емейла**
Сейчас при регистрации при вводе такого же мыла, как у другого пользователя, получаем необработанную ошибку.
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/45819480/164490783-10d69537-3de4-425f-b0f0-5596bd161477.png">
Пользователь с таким не должен сталкиваться. Надо либо возвращать новую страницу-шаблон с человекочитаемым кодом и содержанием ошибки. Либо сделать еще лучше - в случае ошибки, возвращать предзаполненную форму, но у поля формы выводить error с предупреждением, что такой емейл уже существует и занят другим

- **Не замечание, а совет**
Прикольно ты сделал, что взял и подменил поле юзернейма в форме на емейл. Однако, во всех приложениях, где в будущем может потребоваться аутентификация, придется во вью функции делать лишние проверки. 
Можно пойти несколько иными путями
1) https://dev.to/chokshiroshan/how-to-use-email-as-username-for-django-authentication-8if
В этой статье показан способ, как в кастомной модели юзера можно сделать определение  USERNAME_FIELD = 'email' и это будет работать везде
2) Можно вообще переопределить аутентификацию на уровне всей джанги, у нее есть специальная middleware AUTHENTICATION_BACKENDS
https://learndjango.com/tutorials/django-log-in-email-not-username

**Comment by Rogozhin-Dmitry** [comment]
Добрый день, не уверен всё ли у  меня хорошо, но воссоздать такую же ошибку у меня не получилось, в модели у меня вроде прописано, какое сообщение об ошибке отправлять:
![image](https://user-images.githubusercontent.com/62459927/164725609-a93a4a58-2f29-479b-af58-ecbe3b0172b7.png)
![image](https://user-images.githubusercontent.com/62459927/164724611-3a6aac9b-8ee4-4359-9fe9-ceefcda32584.png)
В любом случае на всякий случай прописал вот такую проверку:
![image](https://user-images.githubusercontent.com/62459927/164725738-3ff7d87f-b505-45aa-9c70-365709bf0b10.png)
Статью тоже почитаю и поправлю, но чуть позже

**Comment by keplian** [comment]
Посмотрел - да, проверка такая была у тебя. Сейчас у меня ошибки нет. Возможно какая-то ошибка. Поставлю тебе зачет и допбаллы тогда

**Comment by Rogozhin-Dmitry** [comment]
Отлично, спасибо)))
